name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y qt5-default libsdl1.2-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make
  build-macos:
    name: Build (macOS)
    runs-on: macos-12
    env:
      CPPFLAGS: -DGL_SILENCE_DEPRECATION
    steps:
      - name: Install Dependencies
        run: |
          brew update &&
          brew install coreutils qt5 sdl &&
          brew link --force qt5
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Fixup Framework Paths
        run: |
          cd editor &&
          QT5_PREFIX="`brew --prefix qt5`" &&
          macdeployqt editor.app &&
          prefix="`grealpath $QT5_PREFIX`";
          frameworks=(editor.app/Contents/Frameworks/Qt*.framework) &&
          frameworks=("${frameworks[@]#editor.app/Contents/Frameworks/}") &&
          frameworks=("${frameworks[@]%.framework}") &&
          for framework in "${frameworks[@]}"; do
            for target in "${frameworks[@]}"; do
              install_name_tool -change $prefix/lib/$target.framework/Versions/5/$target @executable_path/../Frameworks/$target.framework/Versions/5/$target editor.app/Contents/Frameworks/$framework.framework/$framework;
            done;
          done;
          for plugin in editor.app/Contents/PlugIns/*/*.dylib; do
            for target in "${frameworks[@]}"; do
              install_name_tool -change $prefix/lib/$target.framework/Versions/5/$target @executable_path/../Frameworks/$target.framework/Versions/5/$target $plugin;
            done;
          done;
      - uses: actions/upload-artifact@v3
        with:
          name: rocket-editor-macos
          path: editor/editor.app
  build-windows:
    name: Build (Windows)
    runs-on: windows-2022
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSVC devenv
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Editor
        run: |
          qmake -tp vc editor/editor.pro
          msbuild editor.vcxproj /v:minimal /property:Configuration=Release /nologo
      - uses: actions/upload-artifact@v3
        with:
          name: rocket-editor-windows
          path: release/editor.exe
